//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Class
    {
        public int Id { get; set; }
        [Required,Display(Name ="Class Name")]
        public string Class_Name { get; set; }
        [Required, Display(Name ="Home Room Teacher")]
        public string HomeRoomTeacher { get; set; }
        [Required, Display(Name ="Class Strength")]
        public Nullable<int> Class_Strength { get; set; }
        [Required]
        public string Designation { get; set; }
        [Required, Display(Name ="Admission Fee")]
        public Nullable<int> Admission_Fee { get; set; }
        [Required, Display(Name = "Tuition Fee")]
        public Nullable<int> Tuition_Fee { get; set; }
        [Required, Display(Name = "Exam Fee")]
        public Nullable<int> Exam_Fee { get; set; }
    }
}
