//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public Nullable<int> Total_Fee { get; set; }
        public Nullable<System.DateTime> Generation_Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
    }
}
