//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }
        [Display(Name = "Student Name")]
        public string Std_Name { get; set; }
        [Display(Name = "Father Name")]
        public string Father_Name { get; set; }
        [Range(minimum: 1, maximum: 100, ErrorMessage = "Age Should be Less then 100 and greater then 0")]
        public Nullable<int> Age { get; set; }
        [StringLength(maximumLength: 200, ErrorMessage = "Maximum length 200 characters")]
        public string Address { get; set; }
        [Display(Name ="Mobile Number"), RegularExpression(@"^([0]{1})+([3]{1})+([0-9]{9})$", ErrorMessage ="the number length should be 11 character format: 03xxxxxxxxx"),StringLength(maximumLength:11,ErrorMessage ="maximum length is 11")]
        public string Contact_Number { get; set; }
        public string Reg_No { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public string Image_Path { get; set; }
    }
}
